### ISSUE TITLE
Export Ascent Style

### ISSUE THREAD

**Issue by lordyavin** [lordyavin/eightanu#4]
The first column of the logbook table contains the ascent style:

![grafik](https://user-images.githubusercontent.com/1528540/83196434-31924280-a13c-11ea-8f1e-da584642f71c.png)

The style is rendered as a SVG circle and the cell does not contain any text.

**Ascent Style:**

![grafik](https://user-images.githubusercontent.com/1528540/83196253-deb88b00-a13b-11ea-9e83-a1374197413b.png)

**Comment by nicHoch** [comment]
style = parent.find("svg").get("title").strip()

**Comment by lordyavin** [comment]
Ha, thanks. Feel free to add this. Note that branch protection is enabled. You need to create a new feature branch to push.
