### ISSUE TITLE
Export Sector

### ISSUE THREAD

**Issue by lordyavin** [lordyavin/eightanu#5]
The ascent logbook does list the top crag only. To retrieve the sector it is necessary to read the details from the route page.

**Comment by nicHoch** [comment]
for the latinized  sector name you can split the url to the route detail.


```
        #https://www.8a.nu/crags/sportclimbing/spain/olba/sectors/casucho/routes/luchar-contra-molinos-de-viento
        #  0   1  2         3      4             5    6     7      8       9       10
```
